# init

In [2]:
import numpy as np
import pandas as pd

# functions

In [ ]:
def highlight_cells(val):
    color = '#FFC6c4' if val == 1 else ''
    style='display:inline'
    return 'background-color: {}'.format(color)

# input

In [ ]:
delta = np.array([\
         [0,1,0,0,0,0,0,0],\
         [0,0,0,0,1,0,0,0],\
         [0,0,0,0,1,1,0,0],\
         [0,0,0,0,0,1,0,0],\
         [0,0,0,0,0,0,0,1],\
         [0,0,0,0,0,0,0,1],\
         [0,0,0,0,0,0,0,1],\
         [0,0,0,0,0,0,0,0]])

In [3]:
df1_styler = pd.DataFrame(delta).style.\
    applymap(highlight_cells).\
    set_table_attributes("style='display:inline'").\
    set_caption('Original boundary matrix')
# display call has to be here 
# even if we change delta to temp_delta, df1 updates to be the 
# same as df2 if we call them at the same time! Super weird.
# consider not using Pandas if it's going to mess up data. 
# is this one of those class issues with python where it 
# updates the object used by the entire class?
display(df1_styler)

# here we alter the matrix
delta[:,5] = (delta[:,4] + delta[:,5]) % 2

df2_styler = pd.DataFrame(delta).style.\
    applymap(highlight_cells).\
    set_table_attributes("style='display:inline'").\
    set_caption('One column addition')


display(df2_styler)